# Generated by Django 4.1.3 on 2022-12-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.IntegerField(choices=[[0, 'Genero'], [1, 'Nacionalidad'], [2, 'Estado Civil'], [3, 'Deporte Preferido'], [4, 'Tipo de Música'], [5, 'Tipo de Comida'], [6, 'Tipo de Bebida'], [7, 'Tipo de Contacto']], verbose_name='Criterio de Selección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
        ),
    ]
